# Generated by Django 3.0.3 on 2020-03-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('course_abbrev', models.CharField(max_length=10, verbose_name='Course Abbreviation')),
                ('course_prof', models.CharField(max_length=20, verbose_name='Course Professor')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Course'),
        ),
    ]
