# Generated by Django 3.0.3 on 2020-02-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200210_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
