# Generated by Django 3.0.3 on 2020-02-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200210_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='end_recur_date',
            field=models.DateTimeField(default='2020-02-17 5:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('HI', 'High'), ('MD', 'Medium'), ('LO', 'Low')], default='LO', max_length=2),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='recur_freq',
            field=models.TextField(default='Never', max_length=7),
            preserve_default=False,
        ),
    ]
