# Generated by Django 3.0.3 on 2020-02-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200217_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='recur_freq',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='DAILY', max_length=7),
        ),
    ]
