# Generated by Django 3.0.3 on 2020-02-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200218_1427'),
        ('todo', '0006_auto_20200217_1917'),
    ]

    operations = [
    ]
