# Generated by Django 3.0.3 on 2020-02-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20200223_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurrence',
            old_name='todo_item',
            new_name='todo',
        ),
    ]
