# Generated by Django 3.0.3 on 2020-02-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20200223_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurrence',
        ),
    ]
