# Generated by Django 3.0.3 on 2020-02-28 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20200228_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 6, 43, 32, 316254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 28, 6, 43, 32, 316254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='end_recur_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 28, 6, 43, 32, 316254, tzinfo=utc)),
        ),
    ]
