# Generated by Django 3.0.3 on 2020-03-01 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20200229_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 15, 19, 39, 488444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 15, 19, 39, 488444, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='end_recur_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 15, 19, 39, 488444, tzinfo=utc)),
        ),
    ]
