# Generated by Django 3.0.3 on 2020-03-01 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20200301_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 22, 11, 12, 191687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='end_recur_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 22, 11, 12, 192781, tzinfo=utc)),
        ),
    ]
