# Generated by Django 3.0.3 on 2020-03-02 02:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_auto_20200301_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 2, 2, 20, 56, 450472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='end_recur_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 2, 2, 20, 56, 451470, tzinfo=utc)),
        ),
    ]
