# Generated by Django 3.0.3 on 2020-03-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_auto_20200301_2120'),
        ('todo', '0023_auto_20200301_1721'),
    ]

    operations = [
    ]
