# Generated by Django 3.0.3 on 2020-03-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_auto_20200301_1721'),
        ('todo', '0019_auto_20200229_2330'),
    ]

    operations = [
    ]
