# Generated by Django 3.0.3 on 2020-03-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_auto_20200302_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('EC', 'Extracurriculars'), ('SC', 'Social'), ('PS', 'Personal'), ('OT', 'Other'), ('NN', 'None')], default='NN', max_length=2),
        ),
    ]
