# Generated by Django 3.0.3 on 2020-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_todoitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('EC', 'Extracurriculars'), ('SC', 'Social'), ('PS', 'Personal'), ('OT', 'Other'), ('NN', 'None')], default='NN', max_length=2, verbose_name='Category'),
        ),
    ]
