# Generated by Django 3.0.3 on 2020-03-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_auto_20200305_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('NN', 'None'), ('AC', 'Academics'), ('EC', 'Extracurriculars'), ('JB', 'Job'), ('SC', 'Social'), ('PS', 'Personal'), ('OT', 'Other')], default='NN', max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('LO', 'Low'), ('MD', 'Medium'), ('HI', 'High')], default='LO', max_length=2),
        ),
    ]
