# Generated by Django 3.0.3 on 2020-03-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_auto_20200306_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('course_abbrev', models.CharField(max_length=10, verbose_name='Course Abbreviation')),
                ('course_prof', models.CharField(max_length=20, verbose_name='Course Professor')),
            ],
        ),
    ]
