# Generated by Django 3.0.3 on 2020-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0031_todoitem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_category_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_description_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_duedate_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_end_recur_date_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_location_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_priority_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_recur_freq_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_title_changed',
            field=models.BooleanField(default=False),
        ),
    ]
