# Generated by Django 3.0.3 on 2020-03-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0032_auto_20200309_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='count',
        ),
    ]
