# Generated by Django 3.0.3 on 2020-03-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0033_remove_todoitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='count_future_events',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_course_changed',
            field=models.BooleanField(default=False),
        ),
    ]
