# Generated by Django 3.0.3 on 2020-03-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0035_auto_20200312_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='has_course_dp_changed',
        ),
    ]
