# Generated by Django 3.0.3 on 2020-03-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0036_remove_todoitem_has_course_dp_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
