# Generated by Django 3.0.3 on 2020-03-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0037_auto_20200313_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('NN', 'None'), ('AC', 'Academics'), ('EC', 'Extracurriculars'), ('JB', 'Job'), ('SC', 'Social'), ('PS', 'Personal'), ('OT', 'Other')], default='NN', max_length=2, verbose_name='Category')),
            ],
        ),
    ]
