# Generated by Django 3.0.3 on 2020-03-13 04:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0039_specific'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=600)),
                ('duedate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('recur_freq', models.CharField(choices=[('NEVER', 'Never'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NEVER', max_length=7)),
                ('end_recur_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('MD', 'Medium'), ('HI', 'High')], default='LO', max_length=2)),
                ('has_title_changed', models.BooleanField(default=False)),
                ('has_description_changed', models.BooleanField(default=False)),
                ('has_duedate_changed', models.BooleanField(default=False)),
                ('has_location_changed', models.BooleanField(default=False)),
                ('has_recur_freq_changed', models.BooleanField(default=False)),
                ('has_end_recur_date_changed', models.BooleanField(default=False)),
                ('has_category_changed', models.BooleanField(default=False)),
                ('has_priority_changed', models.BooleanField(default=False)),
                ('count_future_events', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Category')),
                ('specific', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Specific')),
            ],
        ),
    ]
