# Generated by Django 3.0.3 on 2020-03-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0041_auto_20200313_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=30, verbose_name='Category Name'),
        ),
    ]
