# Generated by Django 3.0.3 on 2020-03-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0043_remove_todoitem_has_category_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('course_abbrev', models.CharField(max_length=10, verbose_name='Course Abbreviation')),
                ('course_prof', models.CharField(max_length=20, verbose_name='Course Professor')),
            ],
        ),
        migrations.RemoveField(
            model_name='specific',
            name='category',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='specific',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='has_category_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('NN', 'None'), ('AC', 'Academics'), ('EC', 'Extracurriculars'), ('JB', 'Job'), ('SC', 'Social'), ('PS', 'Personal'), ('OT', 'Other')], default='NN', max_length=2, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Specific',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Course'),
        ),
    ]
