# Generated by Django 3.0.3 on 2020-03-24 20:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0044_auto_20200313_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('detail', models.CharField(max_length=100, verbose_name='Details')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='End date')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='ec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Extracurricular', verbose_name='Extracurriculars'),
        ),
    ]
