# Generated by Django 3.0.3 on 2020-03-25 05:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0045_auto_20200324_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='future_events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, null=True, size=None),
        ),
    ]
