# Generated by Django 3.0.3 on 2020-03-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0045_auto_20200315_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Course'),
        ),
    ]
