# Generated by Django 3.0.3 on 2020-03-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0046_auto_20200315_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Course'),
        ),
    ]
