# Generated by Django 3.0.3 on 2020-03-17 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0047_auto_20200315_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 17, 1, 21, 32, 906028, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='end_recur_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 17, 1, 21, 32, 906028, tzinfo=utc)),
        ),
    ]
