# Generated by Django 3.0.3 on 2020-03-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0047_remove_todoitem_count_future_events'),
        ('todo', '0024_merge_20200301_2122'),
    ]

    operations = [
    ]
