# Generated by Django 3.0.3 on 2020-03-21 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0049_auto_20200316_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('detail', models.CharField(max_length=100, verbose_name='Details')),
                ('start_time', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('end_time', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='ec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Extracurricular'),
        ),
    ]
