# Generated by Django 3.0.3 on 2020-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0051_auto_20200402_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
