# Generated by Django 3.0.3 on 2020-03-21 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0052_auto_20200321_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracurricular',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='ec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Extracurricular', verbose_name='Extracurriculars'),
        ),
    ]
