# Generated by Django 3.0.3 on 2020-04-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0053_auto_20200411_1337'),
        ('todo', '0052_subtask'),
    ]

    operations = [
    ]
