# Generated by Django 3.0.3 on 2020-03-22 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0053_auto_20200321_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
