# Generated by Django 3.0.3 on 2020-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0054_merge_20200411_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='number_of_subtasks',
            field=models.IntegerField(default=0),
        ),
    ]
